### PR TITLE
Fix dividend logic

### LINKED ISSUE #867: Add another dividend variable and add missing dividend logic
The 0.70.3 code defines three variables related to dividends: `qualified_dividend_income`, `ordinary_dividend_income`, and `dividend_income`.  With 0.70.3 logic, entering $100,000 in `qualified_dividend_income` produces zero income tax liability, and entering $100,000 in `ordinary_dividend_income` produces zero income tax liability.  Entering $100,000 in `dividend_income` produces an income tax liability equal to what the tax on non-qualified dividends would be.

The current version of OpenFisca-US does not seem to have dividend variables and logic specified in a useful manner.  Because qualified and non-qualified dividends are taxed in different ways (at different marginal rates, etc.), it is essential to allow model users a way to specify the difference between qualified and non-qualified dividends.

In [TAXSIM35](https://users.nber.org/~taxsim/taxsim35/), the `dividends` variable is qualified dividends and the `otherprop` variable is where users enter non-qualified dividends and other property income that does not get special tax treatment.

It seems to me that OpenFisca-US needs to add a `non_qualified_dividend_income` variable and remove the `dividend_income` variable.  And it needs to correctly define `ordinary_dividend_income` as the **sum** of `qualified_dividend_income` and `non_qualified_dividend_income`, as indicated in the 2019 Form 1040 instructions for line 3a.

Screen Shot 2022-06-04 at 11 32 06 AM

Once those changes in the basic variables are made (plus any needed changes to the code), the following two tests should pass.

First case 1 with qualified dividend income:

```
# OpenFisca-US test file created by hand
# Expected test output from NBER TAXSIM Model v35 (05/18/22) With TCJA

- name: Tax unit with taxsimid 1
  absolute_error_margin: 0.01
  period: 2019
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 55
        qualified_dividend_income: 100000
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0
    households:
      household:
        members: [person1]
        state_code: TX
  output:
    taxsim_tfica: 0.00
    income_tax: 7263.75
```

Then case 2 with non-qualified dividend income:

```
# OpenFisca-US test file created by hand
# Expected test output from NBER TAXSIM Model v35 (05/18/22) With TCJA

- name: Tax unit with taxsimid 2
  absolute_error_margin: 0.01
  period: 2019
  input:
    people:
      person1:
        is_tax_unit_head: 1
        is_tax_unit_spouse: 0
        is_tax_unit_dependent: 0
        age: 55
        non_qualified_dividend_income: 100000
    tax_units:
      tax_unit:
        members: [person1]
        premium_tax_credit: 0
    households:
      household:
        members: [person1]
        state_code: TX
  output:
    taxsim_tfica: 0.00
    income_tax: 15246.50
```

### PR DESCRIPTION
**Pull request by nikhilwoodruff**
Fixes #867

### CODE REVIEW

**Comment by martinholmer** [comment]
@nikhilwoodruff,  The approach in PR #1197 seems incorrect and uses terms in ways that US tax experts would be confused by.  Ordinary dividends is the sum of qualified and non-qualified dividends as I've pointed out in issue #1187.

**Comment by martinholmer** [comment]
@nikhilwoodruff,  As I've made clear the approach in commit [53d3777] seems to be incorrect (that is, defines variables in ways that are inconsistent with IRS definitions).

However, there is another approach you might consider that would be consistent with IRS definitions.   Here is what that approach would involve:

(1) `qualified_dividend_income` has no formula and a default value of zero (which is, I think, the way it is defined in 0.117.0 version of the code).

(2) `non_qualified_dividend_income` has no formula and a default value of zero (which is, I think, the way it is defined in 0.117.0 version of the code).

(3) `dividend_income` has a formula that defines it as the sum of `qualified_dividend_income` and `non_qualified_dividend_income`.

(4) remove the `ordinary_dividend_income` variable from the model (replacing it with `dividend_income` where necessary)

**Comment by nikhilwoodruff** [comment]
Will aim to complete this by tomorrow.

**Comment by martinholmer** [comment]
@nikhilwoodruff said in PR #1197:
> aiming to complete this by tomorrow. I like your suggestion, so I'll implement that in this PR.

Great!  When you get into the details, if question come up, feel free to drop me a line.

**Pull request merged**
