### PR TITLE
ccdf market rate NY

### LINKED ISSUE #210: Add market rate for CCDF NY
From https://ocfs.ny.gov/main/reports/2019-Child-Care-Market-Rate-Survey.pdf#page=24

Keyed on county cluster, provider type group, duration of care, and child age.

### PR DESCRIPTION
**Pull request by tolaouk**
fixes #210

### CODE REVIEW

**Review by MaxGhenis — APPROVED** [review]

**Comment by MaxGhenis** [comment]
Looks good! Can I merge this?

**Comment by tolaouk** [comment]
> Looks good! Can I merge this?

Yes you can :)

**Comment by nikhilwoodruff** [comment]
One thing before merging (and we should formalise this in policyengine.dev) - could we bump the version (even by a patch) with this? I'd also support starting a proper changelog like in openfisca-core, @MaxGhenis wdyt?

**Comment by MaxGhenis** [comment]
I'd prefer to define our versioning strategy first. PolicyEngine needs consistent version bumps because of its continuous deployment and caching. Adopting that could be cleaner, but keeping track of versions across PRs ends up being a slightly-taxing way of tagging every PR as either a bug fix or new feature. An alternative could be bunchubg them here (though this would admittedly be arbitrary and we may eventually need to switch). Could we wait until a next PR?

**Comment by nikhilwoodruff** [comment]
Ok, yeah. I also do agree on the information duplication. But this PR is definitely good to merge!

**Pull request merged**
